---
- name: Add influxdb repo
  yum_repository:
    name: "influxdb"
    description: "influxdb repo"
    baseurl: "{{influxdb_repo_uri}}"
    gpgkey: "{{influxdb_gpg_key}}"
    state: present

- name: Install InfluxDB package
  yum:
    name: "{{influxdb_pkg_name}}"
    state: present
    update_cache: yes

- name: Install python module for influxdb
  pip:
    name: influxdb
    state: present

- name: Make sure influxd is up
  systemd:
    name: "{{influxdb_pkg_name}}"
    state: started
    enabled: yes
  register: influxdb_up

- name: Pause a while
  pause:
    seconds: "{{influxdb_pausetime}}"
  when: influxdb_up|changed

- name: Create database
  influxdb_database:
    hostname: "{{influxdb_bind_ip}}"
    port: "{{influxdb_port}}"
    database_name: "{{influxdb_db_name}}"
    state: present
  when: influxdb_db_name|length > 0

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of influxdb.monit
  template:
    src: influxdb.monit.j2
    dest: "{{monit_includedir}}/influxdb.monit"
    mode: 0644
  vars:
    pidfile: "{{influxdb_pidfile}}"
    start_program: '/usr/bin/systemctl start {{influxdb_pkg_name}}'
    stop_program: '/usr/bin/systemctl stop {{influxdb_pkg_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
